In [111]:
from CBAStats.Player import *
from CBAStats.Team import *
from CBAStats.Player import stats_output
import numpy as np

df = GameStats().all_games_stats
df

,球员,号码,出场时间,首发,进攻篮板,防守篮板,助攻,犯规,抢断,失误,...,得分,Game_ID,球队,对手,2分中,2分投,3分中,3分投,罚球中,罚球投
0,布鲁克斯,6,36,1,0,3,9,3,2,1,...,27,2019202000001,广东,辽宁,8,10,2,10,5,5
1,任骏飞,20,30,1,1,1,1,3,3,0,...,19,2019202000001,广东,辽宁,5,8,3,6,0,0
2,易建联,9,35,1,1,11,2,2,1,1,...,16,2019202000001,广东,辽宁,7,8,0,0,2,4
3,赵睿,10,31,1,2,5,4,3,2,0,...,10,2019202000001,广东,辽宁,5,9,0,3,0,1
4,胡明轩,3,13,1,0,1,0,1,0,1,...,3,2019202000001,广东,辽宁,0,1,1,3,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8697,刘雁宇,17,0,0,0,0,0,0,0,0,...,0,2019202000250,辽宁,广厦,0,0,0,0,0,0
8698,郭艾伦,13,0,0,0,0,0,0,0,0,...,0,2019202000250,辽宁,广厦,0,0,0,0,0,0
8699,史蒂芬森,1,0,0,0,0,0,0,0,0,...,0,2019202000250,辽宁,广厦,0,0,0,0,0,0
8700,马壮,8,0,0,0,0,0,0,0,0,...,0,2019202000250,辽宁,广厦,0,0,0,0,0,0
8701,丛明晨,10,0,0,0,0,0,0,0,0,...,0,2019202000250,辽宁,广厦,0,0,0,0,0,0

In [131]:
teams

,球队,Game_ID,出场时间,首发,进攻篮板,防守篮板,助攻,犯规,抢断,失误,盖帽,扣篮,被侵,得分,2分中,2分投,3分中,3分投,罚球中,罚球投
0,上海,2019202000008,234,5,11,27,20,21,11,16,2,1,28,93,31,58,5,15,16,27
1,上海,2019202000012,234,5,8,32,19,26,10,17,2,2,24,102,25,48,9,25,25,36
2,上海,2019202000026,235,5,6,29,19,21,9,17,0,2,21,88,30,59,6,18,10,18
3,上海,2019202000037,234,5,10,28,21,21,10,11,5,2,26,94,27,55,7,25,19,21
4,上海,2019202000043,235,5,6,30,23,24,10,14,1,3,19,87,33,52,4,21,9,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
489,青岛,2019202000205,235,5,9,36,21,24,10,17,4,4,24,118,31,54,12,27,20,28
490,青岛,2019202000219,234,5,11,30,17,29,13,9,4,1,32,125,28,55,12,30,33,47
491,青岛,2019202000227,234,5,5,34,16,27,5,9,4,5,25,111,33,55,7,16,24,34
492,青岛,2019202000234,234,5,15,24,15,27,7,6,3,1,30,93,19,50,11,32,22,31
493,青岛,2019202000242,235,5,15,34,17,27,12,12,5,4,29,114,25,49,11,29,31,42

In [129]:
teams = df.groupby(['球队','Game_ID']).sum()
teams= teams.reset_index()
teams.head()

,球队,Game_ID,出场时间,首发,进攻篮板,防守篮板,助攻,犯规,抢断,失误,盖帽,扣篮,被侵,得分,2分中,2分投,3分中,3分投,罚球中,罚球投
0,上海,2019202000008,234,5,11,27,20,21,11,16,2,1,28,93,31,58,5,15,16,27
1,上海,2019202000012,234,5,8,32,19,26,10,17,2,2,24,102,25,48,9,25,25,36
2,上海,2019202000026,235,5,6,29,19,21,9,17,0,2,21,88,30,59,6,18,10,18
3,上海,2019202000037,234,5,10,28,21,21,10,11,5,2,26,94,27,55,7,25,19,21
4,上海,2019202000043,235,5,6,30,23,24,10,14,1,3,19,87,33,52,4,21,9,15

In [128]:
oppteams = df.groupby(['对手','Game_ID']).sum()
oppteams = oppteams.reset_index()
oppteams.head()

,对手,Game_ID,出场时间,首发,进攻篮板,防守篮板,助攻,犯规,抢断,失误,盖帽,扣篮,被侵,得分,2分中,2分投,3分中,3分投,罚球中,罚球投
0,上海,2019202000008,235,5,17,27,14,28,10,17,5,2,21,84,22,47,11,37,7,9
1,上海,2019202000012,235,5,15,26,21,25,10,16,2,1,26,98,26,51,8,31,22,27
2,上海,2019202000026,235,5,5,34,19,21,11,14,2,1,21,94,33,55,5,21,13,15
3,上海,2019202000037,234,5,12,31,13,27,7,15,3,0,21,86,30,57,5,22,11,19
4,上海,2019202000043,235,5,13,30,25,19,11,13,4,3,24,106,22,40,16,41,14,17

In [134]:
merged_stats = teams.merge(oppteams,left_on=['球队','Game_ID'],right_on=['对手','Game_ID'])
merged_stats

,球队,Game_ID,出场时间_x,首发_x,进攻篮板_x,防守篮板_x,助攻_x,犯规_x,抢断_x,失误_x,...,盖帽_y,扣篮_y,被侵_y,得分_y,2分中_y,2分投_y,3分中_y,3分投_y,罚球中_y,罚球投_y
0,上海,2019202000008,234,5,11,27,20,21,11,16,...,5,2,21,84,22,47,11,37,7,9
1,上海,2019202000012,234,5,8,32,19,26,10,17,...,2,1,26,98,26,51,8,31,22,27
2,上海,2019202000026,235,5,6,29,19,21,9,17,...,2,1,21,94,33,55,5,21,13,15
3,上海,2019202000037,234,5,10,28,21,21,10,11,...,3,0,21,86,30,57,5,22,11,19
4,上海,2019202000043,235,5,6,30,23,24,10,14,...,4,3,24,106,22,40,16,41,14,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
489,青岛,2019202000205,235,5,9,36,21,24,10,17,...,4,1,24,108,30,67,8,29,24,31
490,青岛,2019202000219,234,5,11,30,17,29,13,9,...,5,3,29,128,35,57,11,33,25,37
491,青岛,2019202000227,234,5,5,34,16,27,5,9,...,2,0,26,93,21,47,10,28,21,27
492,青岛,2019202000234,234,5,15,24,15,27,7,6,...,6,1,25,104,25,51,12,33,18,23
493,青岛,2019202000242,235,5,15,34,17,27,12,12,...,4,0,26,89,23,56,7,25,22,31

In [ ]:
merged_stats.set

# Module Test

In [2]:
teams_list = list(df['球队'].unique())
teams_list

['广东',
 '辽宁',
 '江苏',
 '浙江',
 '四川',
 '新疆',
 '山东',
 '八一',
 '北控',
 '深圳',
 '青岛',
 '吉林',
 '广厦',
 '福建',
 '上海',
 '同曦',
 '天津',
 '北京',
 '广州',
 '山西']

In [3]:
tm_paces = [Team(team).tm_pace for team in teams_list]

list(zip(teams_list, tm_paces))

[('广东', 98.17750489768116),
 ('辽宁', 94.76428359641743),
 ('江苏', 94.85781585800893),
 ('浙江', 92.95791543771736),
 ('四川', 92.94536374313694),
 ('新疆', 95.99220374889023),
 ('山东', 91.85381428648739),
 ('八一', 91.93159036680748),
 ('北控', 93.24898581751962),
 ('深圳', 91.99471737628596),
 ('青岛', 96.15530471692807),
 ('吉林', 92.46248102319522),
 ('广厦', 93.30386356627324),
 ('福建', 95.52039663854757),
 ('上海', 93.01813708098159),
 ('同曦', 92.53540383092022),
 ('天津', 90.87364237380136),
 ('北京', 88.65089967890698),
 ('广州', 91.66262392394142),
 ('山西', 90.68230011249483)]

In [7]:
tm_posses = [Team(team).tm_poss for team in teams_list]

list(zip(teams_list, tm_posses))

[('广东', 2192.858221185224),
 ('辽宁', 2130.704497501797),
 ('江苏', 2148.064520264256),
 ('浙江', 2018.6261252565564),
 ('四川', 2004.1110320386297),
 ('新疆', 2087.367316836487),
 ('山东', 2076.8232581231077),
 ('八一', 2076.957650458076),
 ('北控', 2114.284655892425),
 ('深圳', 2069.3007552483914),
 ('青岛', 2074.4919763243697),
 ('吉林', 2087.083862326752),
 ('广厦', 2086.517016912211),
 ('福建', 2067.799543913228),
 ('上海', 2102.4940388667123),
 ('同曦', 2091.2612421866693),
 ('天津', 2072.3832345849273),
 ('北京', 1992.1108086238687),
 ('广州', 2089.2774145501025),
 ('山西', 1950.5425198717055)]

# DataFrame test

In [63]:
teams = df.groupby('球队').sum()
teams['首发'] = teams['首发']/5
teams = teams.rename(columns = {'首发':'场次'})
teams

,出场时间,场次,进攻篮板,防守篮板,助攻,犯规,抢断,失误,盖帽,扣篮,被侵,得分,2分中,2分投,3分中,3分投,罚球中,罚球投
球队,,,,,,,,,,,,,,,,,,
上海,5889,25.0,282,728,503,571,242,336,53,63,625,2494,753,1470,183,548,439,653
八一,5860,25.0,310,667,344,599,210,292,62,18,600,2341,650,1440,184,595,489,654
北京,5859,25.0,214,726,499,598,208,322,122,66,564,2441,654,1203,223,632,464,586
北控,5911,25.0,301,785,479,574,239,368,109,47,608,2589,709,1364,222,643,505,659
吉林,5875,25.0,282,710,475,581,227,298,89,58,560,2695,742,1364,241,682,488,623
同曦,5864,25.0,281,712,489,618,202,362,97,57,566,2650,665,1175,295,793,435,550
四川,5658,24.0,290,676,409,650,206,316,46,44,629,2392,587,1223,234,718,516,697
天津,5914,25.0,290,664,435,654,250,418,63,28,584,2398,625,1194,232,716,452,595
山东,5873,25.0,303,777,530,622,236,380,97,85,591,2680,649,1155,307,784,461,611
山西,5639,24.0,276,743,494,502,191,309,110,80,589,2521,644,1170,277,714,402,565
广东,5843,25.0,299,773,554,656,274,343,107,92,594,3023,792,1335,313,784,500,637
广厦,5885,25.0,305,694,524,599,302,321,109,67,602,2600,788,1504,197,562,433,591
广州,5928,25.0,232,705,424,634,173,283,75,41,562,2623,648,1230,299,801,430,549
新疆,5708,24.0,348,786,608,641,205,322,113,87,593,2842,758,1299,272,759,510,700
江苏,5892,25.0,215,733,495,714,208,387,93,75,674,2601,657,1241,240,656,567,735
浙江,5684,24.0,276,619,475,648,261,287,61,35,675,2714,572,1098,334,842,568,711
深圳,5871,25.0,228,699,431,578,245,350,94,112,607,2495,662,1250,231,662,478,659
福建,5663,24.0,272,672,462,569,208,332,71,59,611,2687,704,1301,269,677,472,642
辽宁,5884,25.0,282,779,519,559,233,323,67,95,579,2751,781,1368,223,667,520,697
青岛,5633,24.0,296,749,376,623,208,286,89,62,638,2730,733,1302,244,698,532,725

In [64]:
oppteams = df.groupby('对手').sum().rename(columns = {'首发':'场次'})
oppteams['场次'] = oppteams['场次']/5
oppteams = oppteams.add_prefix('对方')
oppteams

,对方出场时间,对方场次,对方进攻篮板,对方防守篮板,对方助攻,对方犯规,对方抢断,对方失误,对方盖帽,对方扣篮,对方被侵,对方得分,对方2分中,对方2分投,对方3分中,对方3分投,对方罚球中,对方罚球投
对手,,,,,,,,,,,,,,,,,,
上海,5894,25.0,278,776,491,634,226,335,90,74,566,2670,743,1317,257,715,413,542
八一,5871,25.0,255,843,516,608,207,338,119,74,593,2711,791,1377,221,581,466,655
北京,5866,25.0,242,705,428,571,231,336,70,56,592,2379,598,1207,240,669,463,596
北控,5921,25.0,229,704,482,617,243,344,87,74,566,2506,637,1248,256,720,464,617
吉林,5871,25.0,304,707,487,566,213,332,82,65,574,2605,724,1328,240,703,437,585
同曦,5870,25.0,280,682,503,573,231,289,70,66,610,2719,806,1478,207,561,486,658
四川,5661,24.0,278,779,513,635,210,324,121,57,640,2638,637,1178,269,712,557,708
天津,5915,25.0,277,711,524,593,285,344,109,88,646,2787,716,1208,280,748,515,677
山东,5859,25.0,298,642,448,597,262,332,79,45,615,2500,646,1257,249,724,461,652
山西,5643,24.0,243,654,426,599,208,270,91,63,498,2409,655,1282,233,649,400,530
广东,5850,25.0,294,676,448,601,229,372,57,65,654,2604,681,1326,242,710,516,698
广厦,5877,25.0,290,732,484,608,222,432,87,51,588,2530,667,1215,252,718,440,614
广州,5922,25.0,307,785,539,568,193,277,85,67,628,2823,709,1272,299,792,508,677
新疆,5713,24.0,263,652,393,601,214,311,70,45,637,2561,633,1292,250,667,545,712
江苏,5895,25.0,302,756,463,679,270,335,77,59,707,2709,665,1251,253,744,620,820
浙江,5687,24.0,270,693,487,678,187,363,84,81,640,2589,713,1254,203,576,554,728
深圳,5867,25.0,287,769,475,613,226,359,100,55,571,2559,654,1273,277,709,420,560
福建,5647,24.0,335,722,482,615,242,307,93,70,567,2718,729,1330,264,746,468,601
辽宁,5874,25.0,248,703,468,588,247,317,71,55,552,2660,718,1311,269,769,417,537
青岛,5630,24.0,302,706,468,646,182,318,85,61,607,2590,651,1282,259,720,511,672

In [110]:
merged_set = pd.merge(teams,oppteams,left_index=True,right_index=True)
merged_set.loc['江苏']

TypeError: Cannot index by location index with a non-integer key

In [67]:
merged_set.columns

Index(['出场时间', '场次', '进攻篮板', '防守篮板', '助攻', '犯规', '抢断', '失误', '盖帽', '扣篮', '被侵',
       '得分', '2分中', '2分投', '3分中', '3分投', '罚球中', '罚球投', '对方出场时间', '对方场次',
       '对方进攻篮板', '对方防守篮板', '对方助攻', '对方犯规', '对方抢断', '对方失误', '对方盖帽', '对方扣篮',
       '对方被侵', '对方得分', '对方2分中', '对方2分投', '对方3分中', '对方3分投', '对方罚球中', '对方罚球投'],
      dtype='object')

In [ ]:
0.5 * (
    (Tm FGA + 0.4 * Tm FTA - 1.07 * (Tm ORB / (Tm ORB + Opp DRB)) 
     * (Tm FGA - Tm FG) + Tm TOV) + (Opp FGA + 0.4 * Opp FTA - 1.07 * (Opp ORB / (Opp ORB + Tm DRB)) * (Opp FGA - Opp FG) + Opp TOV))

In [79]:
type(merged_set[['出场时间']])

pandas.core.frame.DataFrame

In [80]:
type(merged_set[['场次']])

pandas.core.frame.DataFrame

In [87]:
merged_set = merged_set.astype('float')

In [102]:
merged_set.div(merged_set['场次'],axis='index')

,出场时间,场次,进攻篮板,防守篮板,助攻,犯规,抢断,失误,盖帽,扣篮,...,对方盖帽,对方扣篮,对方被侵,对方得分,对方2分中,对方2分投,对方3分中,对方3分投,对方罚球中,对方罚球投
球队,,,,,,,,,,,,,,,,,,,,,
上海,235.560000,1.0,11.280000,29.120000,20.120000,22.840000,9.680000,13.440000,2.120000,2.520000,...,3.600000,2.960000,22.640000,106.800000,29.720000,52.680000,10.280000,28.600000,16.520000,21.680000
八一,234.400000,1.0,12.400000,26.680000,13.760000,23.960000,8.400000,11.680000,2.480000,0.720000,...,4.760000,2.960000,23.720000,108.440000,31.640000,55.080000,8.840000,23.240000,18.640000,26.200000
北京,234.360000,1.0,8.560000,29.040000,19.960000,23.920000,8.320000,12.880000,4.880000,2.640000,...,2.800000,2.240000,23.680000,95.160000,23.920000,48.280000,9.600000,26.760000,18.520000,23.840000
北控,236.440000,1.0,12.040000,31.400000,19.160000,22.960000,9.560000,14.720000,4.360000,1.880000,...,3.480000,2.960000,22.640000,100.240000,25.480000,49.920000,10.240000,28.800000,18.560000,24.680000
吉林,235.000000,1.0,11.280000,28.400000,19.000000,23.240000,9.080000,11.920000,3.560000,2.320000,...,3.280000,2.600000,22.960000,104.200000,28.960000,53.120000,9.600000,28.120000,17.480000,23.400000
同曦,234.560000,1.0,11.240000,28.480000,19.560000,24.720000,8.080000,14.480000,3.880000,2.280000,...,2.800000,2.640000,24.400000,108.760000,32.240000,59.120000,8.280000,22.440000,19.440000,26.320000
四川,235.750000,1.0,12.083333,28.166667,17.041667,27.083333,8.583333,13.166667,1.916667,1.833333,...,5.041667,2.375000,26.666667,109.916667,26.541667,49.083333,11.208333,29.666667,23.208333,29.500000
天津,236.560000,1.0,11.600000,26.560000,17.400000,26.160000,10.000000,16.720000,2.520000,1.120000,...,4.360000,3.520000,25.840000,111.480000,28.640000,48.320000,11.200000,29.920000,20.600000,27.080000
山东,234.920000,1.0,12.120000,31.080000,21.200000,24.880000,9.440000,15.200000,3.880000,3.400000,...,3.160000,1.800000,24.600000,100.000000,25.840000,50.280000,9.960000,28.960000,18.440000,26.080000
山西,234.958333,1.0,11.500000,30.958333,20.583333,20.916667,7.958333,12.875000,4.583333,3.333333,...,3.791667,2.625000,20.750000,100.375000,27.291667,53.416667,9.708333,27.041667,16.666667,22.083333
广东,233.720000,1.0,11.960000,30.920000,22.160000,26.240000,10.960000,13.720000,4.280000,3.680000,...,2.280000,2.600000,26.160000,104.160000,27.240000,53.040000,9.680000,28.400000,20.640000,27.920000
广厦,235.400000,1.0,12.200000,27.760000,20.960000,23.960000,12.080000,12.840000,4.360000,2.680000,...,3.480000,2.040000,23.520000,101.200000,26.680000,48.600000,10.080000,28.720000,17.600000,24.560000
广州,237.120000,1.0,9.280000,28.200000,16.960000,25.360000,6.920000,11.320000,3.000000,1.640000,...,3.400000,2.680000,25.120000,112.920000,28.360000,50.880000,11.960000,31.680000,20.320000,27.080000
新疆,237.833333,1.0,14.500000,32.750000,25.333333,26.708333,8.541667,13.416667,4.708333,3.625000,...,2.916667,1.875000,26.541667,106.708333,26.375000,53.833333,10.416667,27.791667,22.708333,29.666667
江苏,235.680000,1.0,8.600000,29.320000,19.800000,28.560000,8.320000,15.480000,3.720000,3.000000,...,3.080000,2.360000,28.280000,108.360000,26.600000,50.040000,10.120000,29.760000,24.800000,32.800000
浙江,236.833333,1.0,11.500000,25.791667,19.791667,27.000000,10.875000,11.958333,2.541667,1.458333,...,3.500000,3.375000,26.666667,107.875000,29.708333,52.250000,8.458333,24.000000,23.083333,30.333333
深圳,234.840000,1.0,9.120000,27.960000,17.240000,23.120000,9.800000,14.000000,3.760000,4.480000,...,4.000000,2.200000,22.840000,102.360000,26.160000,50.920000,11.080000,28.360000,16.800000,22.400000
福建,235.958333,1.0,11.333333,28.000000,19.250000,23.708333,8.666667,13.833333,2.958333,2.458333,...,3.875000,2.916667,23.625000,113.250000,30.375000,55.416667,11.000000,31.083333,19.500000,25.041667
辽宁,235.360000,1.0,11.280000,31.160000,20.760000,22.360000,9.320000,12.920000,2.680000,3.800000,...,2.840000,2.200000,22.080000,106.400000,28.720000,52.440000,10.760000,30.760000,16.680000,21.480000
青岛,234.708333,1.0,12.333333,31.208333,15.666667,25.958333,8.666667,11.916667,3.708333,2.583333,...,3.541667,2.541667,25.291667,107.916667,27.125000,53.416667,10.791667,30.000000,21.291667,28.000000

In [107]:
merged_set[['场次']].value

AttributeError: 'DataFrame' object has no attribute 'value'

In [88]:
merged_set.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20 entries, 上海 to 青岛
Data columns (total 36 columns):
出场时间      20 non-null float64
场次        20 non-null float64
进攻篮板      20 non-null float64
防守篮板      20 non-null float64
助攻        20 non-null float64
犯规        20 non-null float64
抢断        20 non-null float64
失误        20 non-null float64
盖帽        20 non-null float64
扣篮        20 non-null float64
被侵        20 non-null float64
得分        20 non-null float64
2分中       20 non-null float64
2分投       20 non-null float64
3分中       20 non-null float64
3分投       20 non-null float64
罚球中       20 non-null float64
罚球投       20 non-null float64
对方出场时间    20 non-null float64
对方场次      20 non-null float64
对方进攻篮板    20 non-null float64
对方防守篮板    20 non-null float64
对方助攻      20 non-null float64
对方犯规      20 non-null float64
对方抢断      20 non-null float64
对方失误      20 non-null float64
对方盖帽      20 non-null float64
对方扣篮      20 non-null float64
对方被侵      20 non-null float64
对方得分      20 non-null float64
对方2分中     20 non-null float64
对方2分投     20 non-null float64
对方3分中     20 non-null float64
对方3分投     20 non-null float64
对方罚球中     20 non-null float64
对方罚球投     20 non-null float64
dtypes: float64(36)
memory usage: 6.4+ KB

In [57]:
team_poss = 0.5 * (
    ((merged_set['2分投']+merged_set['3分投']) + 0.4 * merged_set['罚球投'] - 1.07 * (merged_set['进攻篮板'] / (merged_set['进攻篮板'] + merged_set['防守篮板'])) 
     * ((merged_set['2分投']+merged_set['3分投']) - (merged_set['2分中']+merged_set['3分中'])) + merged_set['失误']) + ((merged_set['对方2分投']+merged_set['对方3分投']) + 0.4 * merged_set['对方罚球投'] - 1.07 * (merged_set['对方进攻篮板'] / (merged_set['对方进攻篮板']+ merged_set['防守篮板'])) * ((merged_set['对方2分投']+merged_set['对方3分投']) - (merged_set['对方2分中']+merged_set['对方3分中'])) + merged_set['对方失误']))

In [58]:
team_poss

0     2285.300994
1     2229.448833
2     2165.385138
3     2309.262595
4     2262.290937
5     2263.059804
6     2183.208898
7     2245.962281
8     2259.993054
9     2138.934277
10    2386.618811
11    2280.551073
12    2257.721512
13    2294.296491
14    2328.539148
15    2178.695181
16    2247.546975
17    2247.425280
18    2336.489221
19    2259.500974
dtype: float64

In [55]:
merged_set.select_dtypes(include=[np.number]).apply(lambda x: x/merged_set['场次'],axis=0)

,出场时间,场次,进攻篮板,防守篮板,助攻,犯规,抢断,失误,盖帽,扣篮,...,对方盖帽,对方扣篮,对方被侵,对方得分,对方2分中,对方2分投,对方3分中,对方3分投,对方罚球中,对方罚球投
0,235.560000,1.0,11.280000,29.120000,20.120000,22.840000,9.680000,13.440000,2.120000,2.520000,...,3.600000,2.960000,22.640000,106.800000,29.720000,52.680000,10.280000,28.600000,16.520000,21.680000
1,234.400000,1.0,12.400000,26.680000,13.760000,23.960000,8.400000,11.680000,2.480000,0.720000,...,4.760000,2.960000,23.720000,108.440000,31.640000,55.080000,8.840000,23.240000,18.640000,26.200000
2,234.360000,1.0,8.560000,29.040000,19.960000,23.920000,8.320000,12.880000,4.880000,2.640000,...,2.800000,2.240000,23.680000,95.160000,23.920000,48.280000,9.600000,26.760000,18.520000,23.840000
3,236.440000,1.0,12.040000,31.400000,19.160000,22.960000,9.560000,14.720000,4.360000,1.880000,...,3.480000,2.960000,22.640000,100.240000,25.480000,49.920000,10.240000,28.800000,18.560000,24.680000
4,235.000000,1.0,11.280000,28.400000,19.000000,23.240000,9.080000,11.920000,3.560000,2.320000,...,3.280000,2.600000,22.960000,104.200000,28.960000,53.120000,9.600000,28.120000,17.480000,23.400000
5,234.560000,1.0,11.240000,28.480000,19.560000,24.720000,8.080000,14.480000,3.880000,2.280000,...,2.800000,2.640000,24.400000,108.760000,32.240000,59.120000,8.280000,22.440000,19.440000,26.320000
6,235.750000,1.0,12.083333,28.166667,17.041667,27.083333,8.583333,13.166667,1.916667,1.833333,...,5.041667,2.375000,26.666667,109.916667,26.541667,49.083333,11.208333,29.666667,23.208333,29.500000
7,236.560000,1.0,11.600000,26.560000,17.400000,26.160000,10.000000,16.720000,2.520000,1.120000,...,4.360000,3.520000,25.840000,111.480000,28.640000,48.320000,11.200000,29.920000,20.600000,27.080000
8,234.920000,1.0,12.120000,31.080000,21.200000,24.880000,9.440000,15.200000,3.880000,3.400000,...,3.160000,1.800000,24.600000,100.000000,25.840000,50.280000,9.960000,28.960000,18.440000,26.080000
9,234.958333,1.0,11.500000,30.958333,20.583333,20.916667,7.958333,12.875000,4.583333,3.333333,...,3.791667,2.625000,20.750000,100.375000,27.291667,53.416667,9.708333,27.041667,16.666667,22.083333
10,233.720000,1.0,11.960000,30.920000,22.160000,26.240000,10.960000,13.720000,4.280000,3.680000,...,2.280000,2.600000,26.160000,104.160000,27.240000,53.040000,9.680000,28.400000,20.640000,27.920000
11,235.400000,1.0,12.200000,27.760000,20.960000,23.960000,12.080000,12.840000,4.360000,2.680000,...,3.480000,2.040000,23.520000,101.200000,26.680000,48.600000,10.080000,28.720000,17.600000,24.560000
12,237.120000,1.0,9.280000,28.200000,16.960000,25.360000,6.920000,11.320000,3.000000,1.640000,...,3.400000,2.680000,25.120000,112.920000,28.360000,50.880000,11.960000,31.680000,20.320000,27.080000
13,237.833333,1.0,14.500000,32.750000,25.333333,26.708333,8.541667,13.416667,4.708333,3.625000,...,2.916667,1.875000,26.541667,106.708333,26.375000,53.833333,10.416667,27.791667,22.708333,29.666667
14,235.680000,1.0,8.600000,29.320000,19.800000,28.560000,8.320000,15.480000,3.720000,3.000000,...,3.080000,2.360000,28.280000,108.360000,26.600000,50.040000,10.120000,29.760000,24.800000,32.800000
15,236.833333,1.0,11.500000,25.791667,19.791667,27.000000,10.875000,11.958333,2.541667,1.458333,...,3.500000,3.375000,26.666667,107.875000,29.708333,52.250000,8.458333,24.000000,23.083333,30.333333
16,234.840000,1.0,9.120000,27.960000,17.240000,23.120000,9.800000,14.000000,3.760000,4.480000,...,4.000000,2.200000,22.840000,102.360000,26.160000,50.920000,11.080000,28.360000,16.800000,22.400000
17,235.958333,1.0,11.333333,28.000000,19.250000,23.708333,8.666667,13.833333,2.958333,2.458333,...,3.875000,2.916667,23.625000,113.250000,30.375000,55.416667,11.000000,31.083333,19.500000,25.041667
18,235.360000,1.0,11.280000,31.160000,20.760000,22.360000,9.320000,12.920000,2.680000,3.800000,...,2.840000,2.200000,22.080000,106.400000,28.720000,52.440000,10.760000,30.760000,16.680000,21.480000
19,234.708333,1.0,12.333333,31.208333,15.666667,25.958333,8.666667,11.916667,3.708333,2.583333,...,3.541667,2.541667,25.291667,107.916667,27.125000,53.416667,10.791667,30.000000,21.291667,28.000000

In [53]:
merged_set.select_dtypes(exclude=[np.number])

    球队 对方球队
0   上海   上海
1   八一   八一
2   北京   北京
3   北控   北控
4   吉林   吉林
5   同曦   同曦
6   四川   四川
7   天津   天津
8   山东   山东
9   山西   山西
10  广东   广东
11  广厦   广厦
12  广州   广州
13  新疆   新疆
14  江苏   江苏
15  浙江   浙江
16  深圳   深圳
17  福建   福建
18  辽宁   辽宁
19  青岛   青岛